"""
ml_model.py – Machine Learning Model Module

Provides pre-trained ML models for URL and email threat classification.
Uses synthetic training data for the MVP; replace with real datasets in production.
Models are serialized to base64 and embedded directly to avoid file-system
dependencies in AWS Lambda.
"""

import numpy as np
import pickle
import base64
import os
import json
from io import BytesIO


# ─── Pre-trained Model Data (Base64-encoded pickle) ──────────────────────────
# These are generated by train_models() and embedded here for Lambda deployment.
# For MVP, we use lightweight models trained on synthetic data.

_URL_MODEL_CACHE = None
_EMAIL_MODEL_CACHE = None


class SimpleLogisticRegression:
    """
    Lightweight Logistic Regression classifier.
    Avoids scikit-learn dependency in Lambda for smaller package size.
    """

    def __init__(self, n_features: int):
        self.weights = np.zeros(n_features)
        self.bias = 0.0
        self.n_features = n_features

    def _sigmoid(self, z):
        z = np.clip(z, -500, 500)
        return 1.0 / (1.0 + np.exp(-z))

    def fit(self, X, y, learning_rate=0.01, epochs=1000):
        """Train the model using gradient descent."""
        X = np.array(X, dtype=np.float64)
        y = np.array(y, dtype=np.float64)
        n_samples = len(X)

        for _ in range(epochs):
            z = np.dot(X, self.weights) + self.bias
            predictions = self._sigmoid(z)

            # Gradients
            dw = (1 / n_samples) * np.dot(X.T, (predictions - y))
            db = (1 / n_samples) * np.sum(predictions - y)

            self.weights -= learning_rate * dw
            self.bias -= learning_rate * db

    def predict_proba(self, X):
        """Return probability of positive class."""
        X = np.array(X, dtype=np.float64)
        z = np.dot(X, self.weights) + self.bias
        return self._sigmoid(z)

    def predict(self, X):
        """Return binary class prediction."""
        return (self.predict_proba(X) >= 0.5).astype(int)

    def serialize(self) -> str:
        """Serialize model to base64 string."""
        data = {
            'weights': self.weights.tolist(),
            'bias': float(self.bias),
            'n_features': self.n_features
        }
        return base64.b64encode(json.dumps(data).encode()).decode()

    @classmethod
    def deserialize(cls, encoded: str) -> 'SimpleLogisticRegression':
        """Deserialize model from base64 string."""
        data = json.loads(base64.b64decode(encoded).decode())
        model = cls(data['n_features'])
        model.weights = np.array(data['weights'])
        model.bias = data['bias']
        return model


class SimpleNaiveBayes:
    """
    Lightweight Gaussian Naive Bayes classifier.
    Avoids scikit-learn dependency for Lambda deployment.
    """

    def __init__(self):
        self.class_priors = {}
        self.means = {}
        self.variances = {}
        self.classes = []

    def fit(self, X, y):
        """Train the model by computing class priors, means, and variances."""
        X = np.array(X, dtype=np.float64)
        y = np.array(y)
        self.classes = np.unique(y).tolist()

        for c in self.classes:
            X_c = X[y == c]
            self.class_priors[c] = len(X_c) / len(X)
            self.means[c] = X_c.mean(axis=0).tolist()
            self.variances[c] = (X_c.var(axis=0) + 1e-9).tolist()  # Smoothing

    def _gaussian_pdf(self, x, mean, var):
        """Compute Gaussian probability density."""
        coeff = 1.0 / np.sqrt(2.0 * np.pi * var)
        exponent = np.exp(-((x - mean) ** 2) / (2.0 * var))
        return coeff * exponent

    def predict_proba(self, X):
        """Return probability of positive class (class 1)."""
        X = np.array(X, dtype=np.float64)
        if X.ndim == 1:
            X = X.reshape(1, -1)

        probabilities = []
        for x in X:
            class_probs = {}
            for c in self.classes:
                prior = np.log(self.class_priors[c])
                likelihood = sum(
                    np.log(self._gaussian_pdf(x[i], self.means[c][i], self.variances[c][i]) + 1e-300)
                    for i in range(len(x))
                )
                class_probs[c] = prior + likelihood

            # Normalize to probability
            max_log_prob = max(class_probs.values())
            total = sum(np.exp(v - max_log_prob) for v in class_probs.values())
            prob_positive = np.exp(class_probs.get(1, class_probs.get(1.0, -1000)) - max_log_prob) / total
            probabilities.append(float(prob_positive))

        return np.array(probabilities)

    def predict(self, X):
        """Return binary class prediction."""
        return (self.predict_proba(X) >= 0.5).astype(int)

    def serialize(self) -> str:
        """Serialize model to base64 string."""
        data = {
            'class_priors': {str(k): v for k, v in self.class_priors.items()},
            'means': {str(k): v for k, v in self.means.items()},
            'variances': {str(k): v for k, v in self.variances.items()},
            'classes': [int(c) for c in self.classes]
        }
        return base64.b64encode(json.dumps(data).encode()).decode()

    @classmethod
    def deserialize(cls, encoded: str) -> 'SimpleNaiveBayes':
        """Deserialize model from base64 string."""
        data = json.loads(base64.b64decode(encoded).decode())
        model = cls()
        model.classes = data['classes']
        model.class_priors = {int(k): v for k, v in data['class_priors'].items()}
        model.means = {int(k): v for k, v in data['means'].items()}
        model.variances = {int(k): v for k, v in data['variances'].items()}
        return model


# ─── Synthetic Training Data Generation ───────────────────────────────────────

def _generate_url_training_data(n_samples=500):
    """
    Generate synthetic URL feature dataset for training.
    Features: domain_age_days, url_length, num_dots, contains_at,
              contains_suspicious_words, https_status, ip_reputation_score,
              num_subdomains, has_ip_address, path_length, num_params,
              suspicious_tld, url_entropy
    """
    np.random.seed(42)
    n_safe = n_samples // 2
    n_malicious = n_samples - n_safe

    # Safe URLs: old domains, short URLs, HTTPS, low suspicion
    safe_features = np.column_stack([
        np.random.randint(365, 3650, n_safe),    # domain_age_days
        np.random.randint(15, 60, n_safe),        # url_length
        np.random.randint(1, 3, n_safe),          # num_dots
        np.zeros(n_safe),                         # contains_at
        np.random.uniform(0, 0.2, n_safe),        # contains_suspicious_words
        np.ones(n_safe),                          # https_status
        np.random.uniform(0, 0.3, n_safe),        # ip_reputation_score
        np.random.randint(0, 2, n_safe),          # num_subdomains
        np.zeros(n_safe),                         # has_ip_address
        np.random.randint(1, 30, n_safe),         # path_length
        np.random.randint(0, 3, n_safe),          # num_params
        np.zeros(n_safe),                         # suspicious_tld
        np.random.uniform(2.5, 4.0, n_safe),     # url_entropy
    ])

    # Malicious URLs: new domains, long URLs, HTTP, high suspicion
    malicious_features = np.column_stack([
        np.random.randint(1, 90, n_malicious),     # domain_age_days
        np.random.randint(50, 200, n_malicious),    # url_length
        np.random.randint(3, 8, n_malicious),       # num_dots
        np.random.choice([0, 1], n_malicious, p=[0.7, 0.3]),  # contains_at
        np.random.uniform(0.4, 1.0, n_malicious),  # contains_suspicious_words
        np.random.choice([0, 1], n_malicious, p=[0.6, 0.4]),  # https_status
        np.random.uniform(0.5, 1.0, n_malicious),  # ip_reputation_score
        np.random.randint(2, 6, n_malicious),       # num_subdomains
        np.random.choice([0, 1], n_malicious, p=[0.6, 0.4]),  # has_ip_address
        np.random.randint(30, 150, n_malicious),    # path_length
        np.random.randint(2, 10, n_malicious),      # num_params
        np.random.choice([0, 1], n_malicious, p=[0.4, 0.6]),  # suspicious_tld
        np.random.uniform(4.0, 6.0, n_malicious),  # url_entropy
    ])

    X = np.vstack([safe_features, malicious_features])
    y = np.concatenate([np.zeros(n_safe), np.ones(n_malicious)])

    # Shuffle
    indices = np.random.permutation(len(X))
    return X[indices], y[indices]


def _generate_email_training_data(n_samples=500):
    """
    Generate synthetic email feature dataset for training.
    Features: urgency_keywords_count, financial_terms_count,
              sender_domain_match, reply_to_mismatch, exclamation_frequency,
              url_count, email_length, caps_ratio, suspicious_attachment_mention
    """
    np.random.seed(43)
    n_safe = n_samples // 2
    n_phishing = n_samples - n_safe

    safe_features = np.column_stack([
        np.random.randint(0, 1, n_safe),          # urgency_keywords_count
        np.random.randint(0, 1, n_safe),          # financial_terms_count
        np.ones(n_safe),                          # sender_domain_match
        np.zeros(n_safe),                         # reply_to_mismatch
        np.random.uniform(0, 0.01, n_safe),       # exclamation_frequency
        np.random.randint(0, 2, n_safe),          # url_count
        np.random.randint(100, 1000, n_safe),     # email_length
        np.random.uniform(0, 0.15, n_safe),       # caps_ratio
        np.zeros(n_safe),                         # suspicious_attachment_mention
    ])

    phishing_features = np.column_stack([
        np.random.randint(2, 8, n_phishing),        # urgency_keywords_count
        np.random.randint(1, 6, n_phishing),        # financial_terms_count
        np.zeros(n_phishing),                        # sender_domain_match
        np.random.choice([0, 1], n_phishing, p=[0.3, 0.7]),  # reply_to_mismatch
        np.random.uniform(0.02, 0.1, n_phishing),   # exclamation_frequency
        np.random.randint(2, 8, n_phishing),        # url_count
        np.random.randint(200, 2000, n_phishing),   # email_length
        np.random.uniform(0.2, 0.6, n_phishing),    # caps_ratio
        np.random.choice([0, 1, 2], n_phishing, p=[0.3, 0.5, 0.2]),  # suspicious_attachment_mention
    ])

    X = np.vstack([safe_features, phishing_features])
    y = np.concatenate([np.zeros(n_safe), np.ones(n_phishing)])

    indices = np.random.permutation(len(X))
    return X[indices], y[indices]


# ─── Model Training & Loading ────────────────────────────────────────────────

def train_url_model() -> SimpleLogisticRegression:
    """Train and return a Logistic Regression model for URL threat detection."""
    X, y = _generate_url_training_data()

    # Normalize features
    X_mean = X.mean(axis=0)
    X_std = X.std(axis=0) + 1e-9
    X_normalized = (X - X_mean) / X_std

    model = SimpleLogisticRegression(n_features=X.shape[1])
    model.fit(X_normalized, y, learning_rate=0.1, epochs=2000)

    # Store normalization params on the model
    model._feature_mean = X_mean
    model._feature_std = X_std

    return model


def train_email_model() -> SimpleNaiveBayes:
    """Train and return a Naive Bayes model for email phishing detection."""
    X, y = _generate_email_training_data()
    model = SimpleNaiveBayes()
    model.fit(X, y)
    return model


def get_url_model() -> SimpleLogisticRegression:
    """Get the URL threat detection model (cached)."""
    global _URL_MODEL_CACHE
    if _URL_MODEL_CACHE is None:
        _URL_MODEL_CACHE = train_url_model()
    return _URL_MODEL_CACHE


def get_email_model() -> SimpleNaiveBayes:
    """Get the email phishing detection model (cached)."""
    global _EMAIL_MODEL_CACHE
    if _EMAIL_MODEL_CACHE is None:
        _EMAIL_MODEL_CACHE = train_email_model()
    return _EMAIL_MODEL_CACHE


def predict_url_threat(features: dict) -> float:
    """
    Predict URL threat probability using the trained model.

    Args:
        features: dict from feature_extractor.extract_url_features()

    Returns:
        float: threat probability (0.0 to 1.0)
    """
    model = get_url_model()
    feature_order = [
        'domain_age_days', 'url_length', 'num_dots', 'contains_at',
        'contains_suspicious_words', 'https_status', 'ip_reputation_score',
        'num_subdomains', 'has_ip_address', 'path_length', 'num_params',
        'suspicious_tld', 'url_entropy'
    ]
    X = np.array([[features.get(f, 0) for f in feature_order]], dtype=np.float64)

    # Normalize using training stats
    if hasattr(model, '_feature_mean'):
        X = (X - model._feature_mean) / model._feature_std

    prob = model.predict_proba(X)
    if isinstance(prob, np.ndarray):
        prob = float(prob[0]) if prob.ndim > 0 else float(prob)
    return round(max(0.0, min(1.0, prob)), 4)


def predict_email_threat(features: dict) -> float:
    """
    Predict email phishing probability using the trained model.

    Args:
        features: dict from feature_extractor.extract_email_features()

    Returns:
        float: phishing probability (0.0 to 1.0)
    """
    model = get_email_model()
    feature_order = [
        'urgency_keywords_count', 'financial_terms_count',
        'sender_domain_match', 'reply_to_mismatch', 'exclamation_frequency',
        'url_count', 'email_length', 'caps_ratio', 'suspicious_attachment_mention'
    ]
    X = np.array([[features.get(f, 0) for f in feature_order]], dtype=np.float64)

    prob = model.predict_proba(X)
    if isinstance(prob, np.ndarray):
        prob = float(prob[0]) if prob.ndim > 0 else float(prob)
    return round(max(0.0, min(1.0, prob)), 4)
